"""
Multi-Variable Predictive Forecasting & Risk Engine
===================================================

Enterprise-grade pipeline for training a multi-variable linear regression model
on historical performance data, generating forward-looking outcome forecasts with
uncertainty quantification, and computing Kelly Criterion-based resource
allocation for dynamic capital/risk management.

Pipeline Stages
---------------
1. **Ingestion & Preprocessing** — Load feature matrix and target vector;
   impute missing values; standardize features via ``StandardScaler``.
2. **Model Training** — Hold-out split; fit ``LinearRegression``; report MSE
   and :math:`R^2` on the test partition.
3. **Prediction & Target Analysis** — Score new observations; return expected
   value (point forecast), variance, and standard deviation of the residual.
4. **Dynamic Allocation** — Translate model edge over a baseline target into
   an optimal allocation percentage using the Kelly Criterion.

Usage
-----
    python predictive_forecasting_engine.py

Input
-----
    historical_performance_data.csv  (generated by ``generate_forecasting_data.py``)

Requirements
------------
    pip install pandas numpy scikit-learn
"""

from __future__ import annotations

import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DATA_FILE = Path("historical_performance_data.csv")
RANDOM_STATE = 42
TEST_SIZE = 0.20

# Feature columns (independent variables / predictors).
FEATURE_COLUMNS: list[str] = [
    "production_efficiency",
    "resource_utilization",
    "efficiency_index",
    "throughput_velocity",
    "system_cool_down",
    "market_volatility_index",
]

# Target column (dependent variable).
TARGET_COLUMN = "outcome_score"

# Risk-management guardrails for Kelly allocation.
MAX_KELLY_FRACTION = 0.25       # Hard cap on full Kelly (fractional Kelly recommended).
KELLY_FRACTIONAL_SCALAR = 0.50  # Half-Kelly dampening for real-world deployment.

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Result containers
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ModelMetrics:
    """Hold-out evaluation metrics for the trained regression model."""

    mse: float
    rmse: float
    r_squared: float
    residual_std: float
    n_train: int
    n_test: int

    def __str__(self) -> str:
        return (
            f"MSE={self.mse:.4f} | RMSE={self.rmse:.4f} | "
            f"R²={self.r_squared:.4f} | Residual σ={self.residual_std:.4f}"
        )


@dataclass(frozen=True)
class PredictionResult:
    """Forecast output with uncertainty quantification."""

    expected_value: float
    variance: float
    std_dev: float
    lower_bound_95: float
    upper_bound_95: float
    feature_contributions: dict[str, float]


@dataclass(frozen=True)
class AllocationResult:
    """Kelly Criterion resource allocation recommendation."""

    baseline_target: float
    predicted_outcome: float
    edge: float
    variance: float
    raw_kelly_fraction: float
    fractional_kelly: float
    capped_allocation_pct: float


# ---------------------------------------------------------------------------
# Data ingestion & preprocessing
# ---------------------------------------------------------------------------


def load_historical_data(path: Path) -> pd.DataFrame:
    """
    Load the historical performance metrics dataset from disk.

    Parameters
    ----------
    path : Path
        CSV file containing feature columns and the target outcome.

    Returns
    -------
    pd.DataFrame
        Raw historical observations.

    Raises
    ------
    FileNotFoundError
        If the data file does not exist.
    """
    if not path.exists():
        raise FileNotFoundError(f"Dataset not found: {path}")
    logger.info("Loading historical data from %s", path)
    return pd.read_csv(path)


def preprocess_features(
    df: pd.DataFrame,
    feature_columns: list[str],
    target_column: str,
) -> tuple[pd.DataFrame, pd.Series]:
    """
    Impute missing feature values and isolate the target vector.

    Missing values in the feature matrix are filled with each column's
    median (robust to outliers). Rows with a missing target are dropped,
    as supervised learning requires a complete response variable.

    Parameters
    ----------
    df : pd.DataFrame
        Raw input frame.
    feature_columns : list[str]
        Names of predictor columns (features).
    target_column : str
        Name of the response variable (target).

    Returns
    -------
    tuple[pd.DataFrame, pd.Series]
        Clean feature matrix ``X`` and target vector ``y``.
    """
    working = df[feature_columns + [target_column]].copy()

    missing_features = working[feature_columns].isna().sum().sum()
    if missing_features > 0:
        logger.warning(
            "Imputing %d missing feature value(s) with column medians.",
            missing_features,
        )
        working[feature_columns] = working[feature_columns].fillna(
            working[feature_columns].median()
        )

    before = len(working)
    working = working.dropna(subset=[target_column])
    dropped = before - len(working)
    if dropped > 0:
        logger.warning("Dropped %d row(s) with missing target values.", dropped)

    X = working[feature_columns]
    y = working[target_column]
    return X, y


def scale_features(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
) -> tuple[np.ndarray, np.ndarray, StandardScaler]:
    """
    Z-score normalize features using training-set statistics only.

    ``StandardScaler`` transforms each feature to zero mean and unit variance,
    ensuring coefficients are comparable and gradient-based solvers converge
    efficiently. Test data is transformed with the *training* scaler to
    prevent information leakage.

    Parameters
    ----------
    X_train : pd.DataFrame
        Training feature matrix.
    X_test : pd.DataFrame
        Hold-out feature matrix.

    Returns
    -------
    tuple[np.ndarray, np.ndarray, StandardScaler]
        Scaled training array, scaled test array, and fitted scaler.
    """
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    return X_train_scaled, X_test_scaled, scaler


# ---------------------------------------------------------------------------
# Model training & evaluation
# ---------------------------------------------------------------------------


def train_regression_model(
    X_train: np.ndarray,
    y_train: pd.Series,
) -> LinearRegression:
    """
    Fit an ordinary least-squares linear regression model.

    The model estimates coefficients :math:`\\beta` that minimize the sum of
    squared residuals between observed targets and linear combinations of
    standardized features: :math:`\\hat{y} = X\\beta`.

    Parameters
    ----------
    X_train : np.ndarray
        Scaled training feature matrix.
    y_train : pd.Series
        Training target vector.

    Returns
    -------
    LinearRegression
        Fitted scikit-learn estimator.
    """
    model = LinearRegression()
    model.fit(X_train, y_train)
    return model


def evaluate_model(
    model: LinearRegression,
    X_test: np.ndarray,
    y_test: pd.Series,
    n_train: int,
) -> tuple[ModelMetrics, np.ndarray]:
    """
    Compute hold-out evaluation metrics and residual distribution.

    Parameters
    ----------
    model : LinearRegression
        Fitted regression estimator.
    X_test : np.ndarray
        Scaled test feature matrix.
    y_test : pd.Series
        Test target vector.
    n_train : int
        Number of training observations (for reporting).

    Returns
    -------
    tuple[ModelMetrics, np.ndarray]
        Structured metrics and the array of test-set residuals.
    """
    y_pred = model.predict(X_test)
    residuals = y_test.values - y_pred

    mse = mean_squared_error(y_test, y_pred)
    rmse = float(np.sqrt(mse))
    r2 = r2_score(y_test, y_pred)

    # Residual standard error (σ̂): degrees-of-freedom adjusted.
    dof = max(len(y_test) - X_test.shape[1] - 1, 1)
    residual_std = float(np.sqrt(np.sum(residuals**2) / dof))

    metrics = ModelMetrics(
        mse=mse,
        rmse=rmse,
        r_squared=r2,
        residual_std=residual_std,
        n_train=n_train,
        n_test=len(y_test),
    )
    return metrics, residuals


def log_model_diagnostics(
    model: LinearRegression,
    feature_columns: list[str],
    metrics: ModelMetrics,
) -> None:
    """Log intercept, feature coefficients, and evaluation metrics."""
    logger.info("--- Model Diagnostics ---")
    logger.info("Intercept (β₀): %.4f", model.intercept_)
    for name, coef in zip(feature_columns, model.coef_):
        logger.info("  Coefficient β[%s]: %+.4f", name, coef)
    logger.info("Train n=%d | Test n=%d", metrics.n_train, metrics.n_test)
    logger.info("Evaluation: %s", metrics)


# ---------------------------------------------------------------------------
# Prediction & target analysis
# ---------------------------------------------------------------------------


def predict_with_uncertainty(
    model: LinearRegression,
    scaler: StandardScaler,
    baseline_features: dict[str, float],
    feature_columns: list[str],
    residual_std: float,
) -> PredictionResult:
    """
    Generate a point forecast with uncertainty bounds for a single observation.

    The **expected value** is the model's point prediction :math:`\\hat{y}`.
    **Variance** is estimated from the residual standard error of the hold-out
    set (:math:`\\hat{\\sigma}^2`), representing irreducible outcome noise not
    captured by the linear feature set. A 95% prediction interval is constructed
    as :math:`\\hat{y} \\pm 1.96\\,\\hat{\\sigma}`.

    Parameters
    ----------
    model : LinearRegression
        Fitted regression estimator.
    scaler : StandardScaler
        Fitted feature scaler from training.
    baseline_features : dict[str, float]
        Current-period feature values keyed by column name.
    feature_columns : list[str]
        Ordered list of predictor names.
    residual_std : float
        Residual standard error from model evaluation.

    Returns
    -------
    PredictionResult
        Forecast with expected value, variance, and confidence bounds.
    """
    feature_vector = pd.DataFrame(
        [{col: baseline_features[col] for col in feature_columns}],
        columns=feature_columns,
    )
    scaled_vector = scaler.transform(feature_vector)
    expected_value = float(model.predict(scaled_vector)[0])

    variance = residual_std**2
    std_dev = residual_std
    margin = 1.96 * std_dev

    # Decompose prediction into per-feature contributions (scaled space).
    contributions = {
        col: float(coef * scaled_vector[0, i])
        for i, (col, coef) in enumerate(zip(feature_columns, model.coef_))
    }

    return PredictionResult(
        expected_value=expected_value,
        variance=variance,
        std_dev=std_dev,
        lower_bound_95=expected_value - margin,
        upper_bound_95=expected_value + margin,
        feature_contributions=contributions,
    )


# ---------------------------------------------------------------------------
# Dynamic capital / resource allocation (Kelly Criterion)
# ---------------------------------------------------------------------------


def kelly_allocation(
    predicted_outcome: float,
    baseline_target: float,
    variance: float,
    max_fraction: float = MAX_KELLY_FRACTION,
    fractional_scalar: float = KELLY_FRACTIONAL_SCALAR,
) -> AllocationResult:
    """
    Compute an optimal resource allocation using the Kelly Criterion.

    In a continuous mean-variance framework, the Kelly fraction that
    maximizes logarithmic utility of wealth is:

    .. math::

        f^* = \\frac{\\mu - r}{\\sigma^2}

    where :math:`\\mu` is the model's expected outcome, :math:`r` is the
    baseline target (risk-free / hurdle rate analogue), and :math:`\\sigma^2`
    is the forecast variance. The **edge** (:math:`\\mu - r`) represents the
    model's expected value above the deployment threshold.

    A **fractional Kelly** scalar (default 0.50, i.e. half-Kelly) is applied
    to reduce drawdown volatility, and the result is capped at ``max_fraction``
    as a hard risk-management constraint.

    Parameters
    ----------
    predicted_outcome : float
        Model expected value (:math:`\\hat{y}`).
    baseline_target : float
        Minimum acceptable outcome / hurdle rate (:math:`r`).
    variance : float
        Forecast variance (:math:`\\hat{\\sigma}^2`).
    max_fraction : float
        Upper bound on deployable capital (default 25%).
    fractional_scalar : float
        Kelly dampening factor (default 0.50 for half-Kelly).

    Returns
    -------
    AllocationResult
        Raw Kelly, fractional Kelly, and capped allocation percentages.
    """
    edge = predicted_outcome - baseline_target

    if variance <= 0:
        logger.warning("Non-positive variance; allocation set to zero.")
        raw_kelly = 0.0
    else:
        raw_kelly = edge / variance

    fractional_kelly = raw_kelly * fractional_scalar
    capped = float(np.clip(fractional_kelly, 0.0, max_fraction))

    return AllocationResult(
        baseline_target=baseline_target,
        predicted_outcome=predicted_outcome,
        edge=edge,
        variance=variance,
        raw_kelly_fraction=raw_kelly,
        fractional_kelly=fractional_kelly,
        capped_allocation_pct=capped * 100,
    )


# ---------------------------------------------------------------------------
# Sample data generator (first-run bootstrap)
# ---------------------------------------------------------------------------


def generate_sample_dataset(path: Path, n_observations: int = 200) -> pd.DataFrame:
    """
    Synthesize a realistic historical performance dataset for demonstration.

    The data-generating process embeds a known linear structure with Gaussian
    noise, enabling the regression model to recover meaningful coefficients
    and produce credible evaluation metrics on first run.

    Parameters
    ----------
    path : Path
        Destination CSV path.
    n_observations : int
        Number of historical periods to simulate.

    Returns
    -------
    pd.DataFrame
        Synthetic dataset written to ``path``.
    """
    rng = np.random.default_rng(RANDOM_STATE)

    production_efficiency = rng.normal(105, 8, n_observations)
    resource_utilization = rng.normal(102, 7, n_observations)
    efficiency = rng.normal(0.52, 0.06, n_observations)
    throughput_velocity = rng.normal(98, 5, n_observations)
    system_cool_down = rng.integers(0, 4, n_observations)
    market_volatility_index = rng.normal(1.0, 0.15, n_observations)

    # Ground-truth data-generating process (target = outcome_score).
    outcome = (
        0.35 * production_efficiency
        + 0.25 * resource_utilization
        + 40.0 * efficiency
        + 0.10 * throughput_velocity
        + 1.50 * system_cool_down
        + 5.0 * market_volatility_index
        + rng.normal(0, 3.5, n_observations)
    )

    df = pd.DataFrame(
        {
            "production_efficiency": production_efficiency,
            "resource_utilization": resource_utilization,
            "efficiency_index": efficiency,
            "throughput_velocity": throughput_velocity,
            "system_cool_down": system_cool_down,
            "market_volatility_index": market_volatility_index,
            "outcome_score": outcome,
        }
    )

    # Inject ~3% missing values to exercise the imputation pipeline.
    mask = rng.random(df.shape) < 0.03
    df = df.mask(mask)

    df.to_csv(path, index=False, float_format="%.4f")
    logger.info("Generated %d-row sample dataset at %s", n_observations, path)
    return df


# ---------------------------------------------------------------------------
# End-to-end pipeline
# ---------------------------------------------------------------------------


def run_forecasting_pipeline(
    data_path: Path = DATA_FILE,
    baseline_target: float = 100.0,
    current_features: Optional[dict[str, float]] = None,
) -> tuple[ModelMetrics, PredictionResult, AllocationResult]:
    """
    Execute the full forecasting and allocation pipeline.

    Parameters
    ----------
    data_path : Path
        Path to the historical metrics CSV.
    baseline_target : float
        Hurdle rate for Kelly edge calculation.
    current_features : dict[str, float], optional
        Feature values for the forward prediction. Defaults to the latest
        row in the training dataset.

    Returns
    -------
    tuple[ModelMetrics, PredictionResult, AllocationResult]
        Evaluation metrics, forecast, and allocation recommendation.
    """
    if not data_path.exists():
        generate_sample_dataset(data_path)

    raw = load_historical_data(data_path)
    X, y = preprocess_features(raw, FEATURE_COLUMNS, TARGET_COLUMN)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE
    )

    X_train_scaled, X_test_scaled, scaler = scale_features(X_train, X_test)

    model = train_regression_model(X_train_scaled, y_train)
    metrics, _ = evaluate_model(model, X_test_scaled, y_test, n_train=len(X_train))
    log_model_diagnostics(model, FEATURE_COLUMNS, metrics)

    if current_features is None:
        current_features = X.iloc[-1].to_dict()

    prediction = predict_with_uncertainty(
        model=model,
        scaler=scaler,
        baseline_features=current_features,
        feature_columns=FEATURE_COLUMNS,
        residual_std=metrics.residual_std,
    )

    allocation = kelly_allocation(
        predicted_outcome=prediction.expected_value,
        baseline_target=baseline_target,
        variance=prediction.variance,
    )

    return metrics, prediction, allocation


def main() -> int:
    """
    Entry point — train model, forecast, and compute allocation.

    Returns
    -------
    int
        Process exit code (0 = success, 1 = failure).
    """
    try:
        # Current-period baseline variables for forward projection.
        current_baseline = {
            "production_efficiency": 112.5,
            "resource_utilization": 104.2,
            "efficiency_index": 0.56,
            "throughput_velocity": 99.8,
            "system_cool_down": 2,
            "market_volatility_index": 1.05,
        }

        metrics, prediction, allocation = run_forecasting_pipeline(
            baseline_target=100.0,
            current_features=current_baseline,
        )

        logger.info("--- Forward Prediction ---")
        logger.info("Expected value (ŷ):     %.2f", prediction.expected_value)
        logger.info("Variance (σ²):          %.4f", prediction.variance)
        logger.info("Std. deviation (σ):     %.4f", prediction.std_dev)
        logger.info(
            "95%% prediction interval: [%.2f, %.2f]",
            prediction.lower_bound_95,
            prediction.upper_bound_95,
        )

        logger.info("--- Kelly Allocation ---")
        logger.info("Baseline target:        %.2f", allocation.baseline_target)
        logger.info("Edge (EV − target):     %+.2f", allocation.edge)
        logger.info("Raw Kelly fraction:     %+.4f", allocation.raw_kelly_fraction)
        logger.info("Fractional Kelly:       %+.4f", allocation.fractional_kelly)
        logger.info(
            "Capped allocation:      %.2f%%",
            allocation.capped_allocation_pct,
        )

        return 0

    except Exception:
        logger.exception("Forecasting pipeline failed.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
